### ISSUE TITLE
Rasa app PostMessageSentHandle

### ISSUE THREAD

**Issue by KheireddineAzzez** [RocketChat/Apps.Rasa#34]
"{"stack":"TypeError: Cannot read property 'getLogger' of undefined\n at Object.exports.createMessage (evalmachine.:39:18)\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at PostMessageSentHandler.run (evalmachine.:45:13)\n at RasaApp.executePostMessageSent (evalmachine.:20:9)","message":"Cannot read property 'getLogger' of undefined"}"

**Comment by dudanogueira** [comment]
Hi!

I have the same problem.

Everything seems to be configured correctly (I have a similar deploy, but with versions 1.1.0 of the app and 3.12.3 of Rocketchat) and got the same error as @KheireddineAzzez 

debug: 2021-06-01T14:28:52.910Z Caller: anonymous OR constructor
[
  "executePostMessageSent is being called..."
]
error: 2021-06-01T14:28:52.920Z Caller: run -> run
[
  "Error occurred while interacting with Rasa Rest API. Details:  Cannot read property 'statusCode' of undefined"
]
error: 2021-06-01T14:28:52.924Z Caller: anonymous OR constructor
[
  "{\"stack\":\"TypeError: Cannot read property 'getLogger' of undefined\\n    at Object.exports.createMessage (evalmachine.<anonymous>:39:18)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at PostMessageSentHandler.run (evalmachine.<anonymous>:45:13)\\n    at RasaApp.executePostMessageSent (evalmachine.<anonymous>:20:9)\",\"message\":\"Cannot read property 'getLogger' of undefined\"}"
]
debug: 2021-06-01T14:28:52.924Z Caller: anonymous OR constructor
[
  "'executePostMessageSent' was unsuccessful."
]

Am I missing something?

**Comment by dudanogueira** [comment]
For instance, the bot works fine when using the integrations hooks.

But when using the APP, I have also this error as mentioned above.
